# Generated by Django 4.1.3 on 2022-11-16 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='title',
        ),
    ]
